package DataDictionaryNew.sandbox;

/*Generated by MPS */


public class IspitnaPrijava {

  private String DatumPrijave;
  private int Ocena;

  private Student prijavio;
  private Predmet Predmet;
  private Profesor potpisao;

  public IspitnaPrijava() {
  }

  public void setDatumPrijave(String newValue) {
    DatumPrijave = newValue;
  }
  public void setOcena(int newValue) {
    Ocena = newValue;
  }

  public void setPrijavio(Student newValue) {
    prijavio = newValue;
  }
  public void setPredmet(Predmet newValue) {
    Predmet = newValue;
  }
  public void setPotpisao(Profesor newValue) {
    potpisao = newValue;
  }


  public String getDatumPrijave() {
    return DatumPrijave;
  }
  public int getOcena() {
    return Ocena;
  }

  public Student getPrijavio() {
    return prijavio;
  }
  public Predmet getPredmet() {
    return Predmet;
  }
  public Profesor getPotpisao() {
    return potpisao;
  }

}
