package DataDictionaryNew.sandbox;

/*Generated by MPS */


public class Mesto {

  private int MestoId;
  private String Naziv;


  public Mesto() {
  }

  public void setMestoId(int newValue) {
    MestoId = newValue;
  }
  public void setNaziv(String newValue) {
    Naziv = newValue;
  }



  public int getMestoId() {
    return MestoId;
  }
  public String getNaziv() {
    return Naziv;
  }


}
