package DataDictionaryNew.sandbox;

/*Generated by MPS */


public class Osoaba {

  private int OsobaId;
  private String Naziv;


  public Osoaba() {
  }

  public void setOsobaId(int newValue) {
    OsobaId = newValue;
  }
  public void setNaziv(String newValue) {
    Naziv = newValue;
  }



  public int getOsobaId() {
    return OsobaId;
  }
  public String getNaziv() {
    return Naziv;
  }


}
