package DataDictionaryNew.sandbox;

/*Generated by MPS */

import java.util.List;

public class Osoba {

  private int OsobaId ;
  private String Ime;
  private double Prezime ;
  private String Godina;

  private Mesto Mesto;
  private List<Mesto> MetoList;
  private Prijava Prijava;
  private Mesto A;

  public Osoba() {
  }

  public void setOsobaId (int newValue) {
    OsobaId  = newValue;
  }
  public void setIme(String newValue) {
    Ime = newValue;
  }
  public void setPrezime (double newValue) {
    Prezime  = newValue;
  }
  public void setGodina(String newValue) {
    Godina = newValue;
  }

  public void setMesto(Mesto newValue) {
    Mesto = newValue;
  }
  public void setMetoList(List<Mesto> newValue) {
    MetoList = newValue;
  }
  public void setPrijava(Prijava newValue) {
    Prijava = newValue;
  }
  public void setA(Mesto newValue) {
    A = newValue;
  }


  public int getOsobaId () {
    return OsobaId ;
  }
  public String getIme() {
    return Ime;
  }
  public double getPrezime () {
    return Prezime ;
  }
  public String getGodina() {
    return Godina;
  }

  public Mesto getMesto() {
    return Mesto;
  }
  public List<Mesto> getMetoList() {
    return MetoList;
  }
  public Prijava getPrijava() {
    return Prijava;
  }
  public Mesto getA() {
    return A;
  }

}
