package DataDictionaryNew.sandbox;

/*Generated by MPS */


public class Predmet {

  private int SifraPredmeta;
  private String NazivPredmeta;


  public Predmet() {
  }

  public void setSifraPredmeta(int newValue) {
    SifraPredmeta = newValue;
  }
  public void setNazivPredmeta(String newValue) {
    NazivPredmeta = newValue;
  }



  public int getSifraPredmeta() {
    return SifraPredmeta;
  }
  public String getNazivPredmeta() {
    return NazivPredmeta;
  }


}
