package DataDictionaryNew.sandbox;

/*Generated by MPS */


public class Prijava {

  private int PrijavaId;
  private String Naziv;


  public Prijava() {
  }

  public void setPrijavaId(int newValue) {
    PrijavaId = newValue;
  }
  public void setNaziv(String newValue) {
    Naziv = newValue;
  }



  public int getPrijavaId() {
    return PrijavaId;
  }
  public String getNaziv() {
    return Naziv;
  }


}
