package DataDictionaryNew.sandbox;

/*Generated by MPS */


public class Profesor {

  private String ImeProfesora;
  private String PrezimeProfesora;


  public Profesor() {
  }

  public void setImeProfesora(String newValue) {
    ImeProfesora = newValue;
  }
  public void setPrezimeProfesora(String newValue) {
    PrezimeProfesora = newValue;
  }



  public String getImeProfesora() {
    return ImeProfesora;
  }
  public String getPrezimeProfesora() {
    return PrezimeProfesora;
  }


}
