package DataDictionaryNew.sandbox;

/*Generated by MPS */

import java.util.List;

public class Racun {

  private int BrojRacuna;
  private String Datum;

  private List<Stavka> Stavka;
  private Radnik Radnik;

  public Racun() {
  }

  public void setBrojRacuna(int newValue) {
    BrojRacuna = newValue;
  }
  public void setDatum(String newValue) {
    Datum = newValue;
  }

  public void setStavka(List<Stavka> newValue) {
    Stavka = newValue;
  }
  public void setRadnik(Radnik newValue) {
    Radnik = newValue;
  }


  public int getBrojRacuna() {
    return BrojRacuna;
  }
  public String getDatum() {
    return Datum;
  }

  public List<Stavka> getStavka() {
    return Stavka;
  }
  public Radnik getRadnik() {
    return Radnik;
  }

}
