package DataDictionaryNew.sandbox;

/*Generated by MPS */


public class Radnik {

  private int Ime;
  private int Prezime;
  private String DatumZaposlenja;


  public Radnik() {
  }

  public void setIme(int newValue) {
    Ime = newValue;
  }
  public void setPrezime(int newValue) {
    Prezime = newValue;
  }
  public void setDatumZaposlenja(String newValue) {
    DatumZaposlenja = newValue;
  }



  public int getIme() {
    return Ime;
  }
  public int getPrezime() {
    return Prezime;
  }
  public String getDatumZaposlenja() {
    return DatumZaposlenja;
  }


}
