package DataDictionaryNew.sandbox;

/*Generated by MPS */


public class Stavka {

  private int RedniBroj;
  private String Proizvod;
  private int Cena;
  private int Kolicina;


  public Stavka() {
  }

  public void setRedniBroj(int newValue) {
    RedniBroj = newValue;
  }
  public void setProizvod(String newValue) {
    Proizvod = newValue;
  }
  public void setCena(int newValue) {
    Cena = newValue;
  }
  public void setKolicina(int newValue) {
    Kolicina = newValue;
  }



  public int getRedniBroj() {
    return RedniBroj;
  }
  public String getProizvod() {
    return Proizvod;
  }
  public int getCena() {
    return Cena;
  }
  public int getKolicina() {
    return Kolicina;
  }


}
