package DataDictionaryNew.sandbox;

/*Generated by MPS */


public class Student {

  private String ImeStudenta;
  private String PrezimeStudenta;
  private String BrojIndeksa;


  public Student() {
  }

  public void setImeStudenta(String newValue) {
    ImeStudenta = newValue;
  }
  public void setPrezimeStudenta(String newValue) {
    PrezimeStudenta = newValue;
  }
  public void setBrojIndeksa(String newValue) {
    BrojIndeksa = newValue;
  }



  public String getImeStudenta() {
    return ImeStudenta;
  }
  public String getPrezimeStudenta() {
    return PrezimeStudenta;
  }
  public String getBrojIndeksa() {
    return BrojIndeksa;
  }


}
